# Generated by Django 4.2.6 on 2023-10-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='next',
        ),
        migrations.AddField(
            model_name='task',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='tasks.task'),
        ),
    ]
