# Generated by Django 4.2.6 on 2023-10-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcolorgroup',
            name='name',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
