# Generated by Django 4.2.6 on 2023-10-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectcolorgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcolorgroup',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
